// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/yqwoe/.nvm/versions/node/v16.19.0/lib/node_modules/dumi/dist/client/theme-api/index.js';
