// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/yqwoe/.nvm/versions/node/v16.19.0/lib/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from '/Users/yqwoe/.nvm/versions/node/v16.19.0/lib/node_modules/dumi/theme-default/slots/SearchBar/index.js';
